services:
  - type: web
    name: genomic-annotation-api
    env: docker
    plan: starter
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: ENV
        value: production
      - key: CORS_ALLOW_ORIGINS
        value: "*"  # set to your static site origin
      - key: MAX_UPLOAD_MB
        value: "50"
      # Optional Redis (Upstash) for jobs/cache
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false

services:
  - type: web
    name: genomic-annotation
    env: docker
    plan: free
    region: frankfurt   # or virginia if more US users
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /ping

